(lang dune 2.5)
(using coq 0.2)

(generate_opam_files true)
(allow_approximate_merlin)

(name koika)
(version 0.0.1)

(package
 (name koika)
 (depends)
 (synopsis "Specification and verification of strong timing isolation for hardware enclaves")
 (description ""))
